# Deep Learning

# Tutorial 2: Tensors

In this tutorial, we will cover:

- PyTorch Tensors: creation, gpu tensors, shape manipulation, indexing

Prerequisites:

- Python

Our contacts:

- Niklas Beuter (niklas.beuter@th-luebeck.de)
- Fenja Falta (fenja.falta@th-luebeck.de)

Course:

- Slides and notebooks will be available at https://lernraum.th-luebeck.de/course/view.php?id=5383


# Introduction to PyTorch Tensors

There are several Deep Learning frameworks like [PyTorch](https://pytorch.org/), [Tensorflow](https://www.tensorflow.org/) and others. As PyTorch is one of the most used frameworks and great to learn, we will mainly focus on PyTorch throughout the course.  

PyTorch tensors are the fundamental building blocks of the PyTorch library, offering a powerful way to store and operate on data. Tensors are similar to NumPy arrays but have additional capabilities, such as GPU support, that make them suitable for deep learning tasks. In this notebook, we'll explore the basics of creating and manipulating tensors in PyTorch.

Before we dive into Tensors, it might be useful to learn the basics of Python Numpy.


In [2]:
### EXECUTE AT THE BEGINNING OF THE COURSE TO INSTALL DEPENDENCIES
!pip install numpy torch typing torchvision matplotlib scikit-image

# Introduction to NumPy

NumPy is one of the most widely used Python libraries in data science and scientific computing. It stands for Numerical Python and provides an efficient interface to store and operate on dense data buffers. In this notebook, we will cover some basic aspects of NumPy, including array creation, array attributes, and basic operations.


In [3]:
# Importing NumPy
import numpy as np

## Creating NumPy Arrays

NumPy arrays are homogeneous in nature, i.e., they contain elements of the same data type. They are created using the `np.array` function. Here are a few examples:

In [4]:
# Creating a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr_1d)

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr_2d)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]


## Array Attributes

Each NumPy array has attributes that help you understand its nature. Some of the most important ones are `shape`, `size`, `dtype`, and `ndim` (number of dimensions).

In [6]:
# Exploring array attributes
print("Shape of arr_2d:", arr_2d.shape)
print("Size of arr_2d:", arr_2d.size)
print("Data type of arr_2d:", arr_2d.dtype)
print("Number of dimensions of arr_2d:", arr_2d.ndim)

Shape of arr_2d: (2, 3)
Size of arr_2d: 6
Data type of arr_2d: int64
Number of dimensions of arr_2d: 2


## Basic Operations

NumPy arrays support various mathematical operations that can be performed element-wise, along with aggregation operations like sum, mean, etc. Here's a quick look at some basic operations:

In [7]:
# Basic arithmetic operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Addition
print("a + b =", a + b)

# Element-wise multiplication
print("a * b =", a * b)

# Aggregation
print("Sum of a:", np.sum(a))

a + b = [ 6  8 10 12]
a * b = [ 5 12 21 32]
Sum of a: 10


## Indexing and Slicing

NumPy arrays can be sliced and indexed similar to Python lists, but with more flexibility. Do not be confused by the writing in the array. The slicing "1:3" and ":" will be explained later in the chapter.

In [ ]:
# Indexing a 2D array (Matrix)
print("Element at row 1, column 2:", arr_2d[1, 2])

# Slicing
print("First row:", arr_2d[0, :])
print("First column:", arr_2d[:, 0])
print("Subarray:", arr_2d[:, 1:3])

## Traversion from Numpy to Tensors

So, why do we need Tensors?

Tensors and NumPy arrays are both efficient data containers, but tensors offer several key advantages, particularly in the context of deep learning:

1. **Compatibility with GPUs and Distributed Computing**
   - Tensors are optimized for performance on GPUs and TPUs, allowing for significantly faster computations necessary for training deep learning models. NumPy arrays, by contrast, are primarily designed to run on CPUs. This distinction is crucial for the computational demands of modern deep learning tasks.

2. **Automatic Differentiation**
   - Deep learning frameworks that use tensors, such as PyTorch and TensorFlow, provide automatic differentiation capabilities. This allows for the easy calculation of gradients, which are essential for training neural networks. NumPy lacks built-in support for automatic differentiation.

3. **Advanced Deep Learning Operations**
   - Tensors are integrated into deep learning libraries that offer a wide range of predefined operations specifically designed for building and training neural networks, such as convolutional operations, pooling, and various activation functions. While similar operations can be implemented using NumPy, tensors provide these as optimized, ready-to-use functions.

4. **Dynamic Computation Graphs**
   - Libraries like PyTorch use tensors to create dynamic computation graphs, making it easier to build models that change their behavior dynamically at runtime. This is particularly useful for models that vary their structure based on input data, something that is not directly supported with NumPy arrays.


- Numpy tensors and PyTorch tensors are very similar, most of the features that we will explain for PyTorch tensors apply to Numpy tensors.
- In real DL systems you need to constantly switch between the two.

In the course, we will constantly name **n-dimensional arrays as tensors**.

If you have previous knowledge in Matlab, you could read following [numpy for Matlab users page](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) as a useful resource.

# Working with PyTorch Tensors

## Importing PyTorch

In order to start with PyTorch Tensors let's import the PyTorch library. If PyTorch is not installed, you can install it using pip (`pip install torch`).

During the course we'll use and learn many parts of its API.
You should also familiarize with the [PyTorch Documentation](https://pytorch.org/docs/stable/) as it will greatly assist you.

In [ ]:
import torch
torch.__version__

## Creating Tensors

PyTorch provides several functions to create tensors. Let's start by creating tensors in various ways.
Each tensor consists of several values of the same type. It can have arbitrary dimensions (n-dimensional grid).

In [ ]:
# Creating a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print("Tensor from list:", tensor_from_list)

# Creating a tensor from a list with two dimensions as type in32
tensor_from_list = torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.int32)
print("Tensor from list with two dimensions:", tensor_from_list)

# Creating a tensor with a specific size filled with zeros
tensor_of_zeros = torch.zeros((3, 3))
print("\nTensor of zeros:\n", tensor_of_zeros)

# Creating a tensor with random values
random_tensor = torch.rand((2, 2))
print("\nRandom tensor:\n", random_tensor)

# Creating a tensor all filled with ones as type float64
tensor_of_ones = torch.ones((2,5), dtype=torch.float64)
print("\nTensor of ones:\n", tensor_of_ones)

> **EXERCISE**
>
> Take a look at the Python [documentation](https://docs.pytorch.org/docs/main/generated/torch.eye.html) of `torch.eye` to create a matrix $M \in R^{3 \times 3}$ that is filled with 1 along the diagonal and 0 elsewhere, that is:
>
> $$
m_{ij} = \left[ \begin{array}{rrr}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{array}\right]
$$

In [ ]:
# TODO

> **EXERCISE**
>
> Create a matrix $M \in R^{3 \times 3}$ that is filled with 2 along the diagonal and 1 elsewhere, that is:
>
> $$
m_{ij} =
\begin{cases}
2 & \text{if } i = j \\
1 & \text{otherwise}
\end{cases}
$$

In [ ]:
# TODO

## Tensor properties

The **type** of a tensor is the type of each element contained in the tensor:

In [ ]:
t = torch.rand((3, 3))
t.dtype


The **shape** of a tensor is a tuple of integers giving the size of the tensor along each dimension, e.g. for a matrix $M \in R^{3 \times 5}$:

In [ ]:
t = torch.rand((3,5))
t.shape

> **EXERCISE**
>
> Given a matrix $X \in R^{m \times n}$, create another matrix $Y \in R^{m \times n}$ filled with ones.  Tip, use `torch.ones_like` ([documentation](https://docs.pytorch.org/docs/stable/generated/torch.ones_like.html)).

In [ ]:
# TODO

The used function is useful when you need a tensor of ones that matches the dimensions of another tensor for operations that require such a structure, like initializing weights in neural networks or performing operations that involve adding a tensor of ones.

## Tensor rank

In **Numpy** and **PyTorch** the **rank** means **number of dimensions** (different meaning from matrix rank in linear algebra!)

In [ ]:
from typing import Union

# Utility print function
def print_arr(*arr: Union[torch.Tensor, np.ndarray], prefix: str = "") -> None:
    """ Pretty print tensors, together with their shape and type

    :param arr: one or more tensors
    :param prefix: prefix to use when printing the tensors
    """
    print(
        "\n\n".join(
            f"{prefix}{str(x)} <shape: {x.shape}> <dtype: {x.dtype}>" for x in arr
        )
    )

- **rank-0** tensors are just scalars

In [ ]:
t0 = torch.tensor(3, dtype=torch.double)

print_arr(t0)

In [ ]:
item = t0.item()  # convert tensor scalar to a python base type
item, type(item)

- **rank-1** tensors of length ``n`` have a shape of ``(n,)``

In [ ]:
# A rank-1 array
t1 = torch.tensor([1, 2, 3])

print_arr(t1)

In [ ]:
# A rank-1 array with a single scalar
print_arr(torch.tensor([42]))

- **rank-2** tensors have a shape of ``(n, m)``

In [ ]:
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])

print_arr(t2)

In [ ]:
# A column vector is a rank-2 tensor
t_col = t1.reshape(-1, 1)

print_arr(t_col)

In [ ]:
# A row vector is a rank-2 tensor
t_row = t1.reshape(1, -1)

print_arr(t_row)

> **NOTE**
>
> The rank-1 tensors are consider to be both row and column tensors

- **rank-k** tensors have a shape of $(n_1, \dots, n_k)$

In [ ]:
print_arr(torch.zeros((2, 3, 4)))

In [ ]:
print_arr(torch.ones((2, 2, 2, 2)))

> **EXERCISE**
>
> Build a tensor $X \in R^{4 \times 4}$ filled with zeros and the sequence $[0, 1, 2, 3]$ along the diagonal

In [ ]:
# TODO

In [ ]:
# TODO

> **EXERCISE**
>
> Which is the shape of the following tensor?
>
> ```
> tensor([[[1., 1.],
>           [1., 1.]],
>
>          [[1., 1.],
>           [1., 1.]],
>
>          [[1., 1.],
>           [1., 1.]],
>
>          [[1., 1.],
>           [1., 1.]]])
> ```

In [ ]:
# TODO

## Tensor Operations

Tensors support a variety of operations, including mathematical operations, slicing, and reshaping. Here are a few examples.


In [ ]:
# Addition
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
sum_tensors = tensor_a + tensor_b
print("Sum of tensors:", sum_tensors)

# Reshaping
initial_tensor = torch.rand((2, 3))
reshaped_tensor = initial_tensor.view(3, 2)
print("\nInitial tensor:\n", initial_tensor)
print("\nReshaped tensor:\n", reshaped_tensor)

# Slicing
tensor_c = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sliced_tensor = tensor_c[:, 1]  # All rows, second column
print("\nSliced tensor:", sliced_tensor)


## Changing and adding dimensions

PyTorch provides several functions to manipulate tensor's shapes


## Transpose dimension

Transpose means to change columns and rows accordingly.

In [ ]:
a = torch.ones((3, 5))
a[0, -1] = 0
print_arr(a)

In [ ]:
a.transpose(1, 0)  # Swap dimension 1 and 0

In [ ]:
# It is possible to transpose in k-dimensions
a = torch.ones((2, 3, 6))
a[1, 2, 4] = 42
print_arr(a)

In [ ]:
a.transpose(2, 1)

> **NOTE**
>
> In Numpy the transpose function is different!

In [ ]:
a = np.arange(10).reshape(2, 5)
a

In [ ]:
a.transpose(0, 1)

In [ ]:
a.transpose(1, 0)

## Tensor to NumPy and Vice Versa

It's common to convert between PyTorch tensors and NumPy arrays. PyTorch provides easy ways to perform these conversions.


In [ ]:
import numpy as np

# Tensor to NumPy array
tensor_d = torch.tensor([7, 8, 9])
numpy_array = tensor_d.numpy()
print("NumPy array from tensor:", numpy_array)

# NumPy array to tensor
np_array = np.array([10, 11, 12])
tensor_from_np = torch.from_numpy(np_array)
print("\nTensor from NumPy array:", tensor_from_np)


## Reshape

Another important feature is **reshaping** a tensor into different dimensions

- We need to make sure to **preserve the same number of elements**.
- Use `-1` in one of the dimensions to tell numpy to **figure it out**.


Pay attention that **transposing and reshaping are two fundamentally different operations**:

In [ ]:
a = torch.arange(12).reshape(3,4 )
a

In [ ]:
# The classical transpose
a.t()

In [ ]:
# Reshape into the transpose shape
a.reshape(4, 3)

Think of the `reshape` operations as unrolling the tensor **row-wise**, to obtain a rank-1 tensor. Then organize the values in this tensor following the specified dimensions.

```
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
```
$ \to $
```
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

Then, starting from the right-most dimension's size, organize the values into the dimensions

- e.g. reshape into `[4, 3]`:
```
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```
$ \to $
```
tensor([[0,  1,  2],  [3,  4,  5],  [6,  7,  8],  [9, 10, 11]])
```
$ \to $
```
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
```

- e.g. reshape into `[2, 2, 3]`:
```
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```
$ \to $
```
tensor([[0,  1,  2],  [3,  4,  5],  [6,  7,  8],  [9, 10, 11]])
```
$ \to $
```
tensor([[[0,  1,  2],  [3,  4,  5]],  [[6,  7,  8],  [9, 10, 11]]])
```
$ \to $
```
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
```

In [ ]:
a = torch.arange(12)
print_arr(a)

In [ ]:
a.reshape(6, 2)

In [ ]:
a.reshape(2, 6)

In [ ]:
a.reshape(2, 2, 3)

In [ ]:
try:
  a.reshape(5, -1)
except RuntimeError as e:
  print(e)

In [ ]:
a.reshape(1, -1)

In [ ]:
a.reshape(-1, 1)

In [ ]:
a.reshape(-1)

> **NOTE**
>
> We can add or remove dimensions of size `1` using `torch.unsqueeze` or `torch.squeeze`

> **NOTE**
>
> If you want to be sure to obtain a reshaped view of the tensor, sharing the same underlying data avoiding copying data, you can use the `torch.view` method.
> It's semantic is similar to `reshape`, but it works only on `contiguous` tensors and it guarantees that no copy will be performed.

## Concatenation

PyTorch provides many functions to manipulate tensors.
Two of the most common functions are:

- `torch.stack`: Concatenates sequence of tensors along a new dimension.
- `torch.cat`: Concatenates the given sequence of seq tensors in the given dimension.

In [ ]:
a = torch.arange(12).reshape(3, 4)
b = torch.arange(12).reshape(3, 4) + 100
print_arr(a, b)

In [ ]:
out = torch.cat((a, b), dim=0)
print_arr(out)

In [ ]:
out = torch.stack((a, b), dim=0)
print_arr(out)

> **EXERCISE**
>
> Given a rank-1 array of increasing numbers from `0` to `9`, defined as:
>

In [ ]:
a = torch.arange(10)
a

> Use only the `reshape` and `transpose` function to obtain the following tensor from `a`:
>
> ```python
> tensor([[0, 2, 4, 6, 8],
>         [1, 3, 5, 7, 9]])
> ```

In [ ]:
# TODO

> **EXERCISE**
>
> Given a tensor $X \in R^{3 \times 5 \times 8 \times 10}$ reshape it in order to obtain a tensor $Y \in R^{10 \times 8 \times 3 \times 5}$

In [ ]:
x = torch.rand(3, 5, 8, 10)
x.shape
y = []

# TODO


In [ ]:
# TESTS

## Tensor indexing

PyTorch offers several ways to index tensors


### **Standard indexing**

As standard Python lists, PyTorch tensors support the python indexing convenctions:

In [ ]:
a = torch.arange(10)
a

In [ ]:
print(a[0])  # first element
print(a[1])  # second element

In [ ]:
print(a[-1])  # last element
print(a[-2])  # second last element

### **Multidimensional indexing**

Since tensors may be multidimensional, you must specify **one index for each dimension**:

In [ ]:
a = torch.arange(10).reshape(2, 5)
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[0, -1]

## **Slicing**

Similar to Python lists and Numpy arrays, PyTorch tensors can be easily sliced using the slice notation:

```python
a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array
```

There is also the step value, which can be used with any of the above:

```python
a[start:stop:step] # start through not past stop, by step
```

In [ ]:
a = torch.arange(10)
a

In [ ]:
# Take the last 5 elements
a[-5:]

In [ ]:
# Index every element in a even index
a[::2]

> **NOTE**
>
> Remember that the **slice syntax** is just a shorthand.
>
> In Python everything is an object, even a ``slice``.
> It is possible to explicitly create a ``Slice`` object and reuse it to **index multiple tensors in the same way**:


In [ ]:
# The signature follows the same pattern as above
s1 = slice(3)  # equivalent to the slice :3
s1

In [ ]:
type(s1)  # It is a built-in type

In [ ]:
out = a[s1]  # equivalent to a[:3]

print_arr(a, out)

In [ ]:
mystring = 'this is just a string'
mystring[s1]

In [ ]:
s2 = slice(None, None, -1)
mystring[s2]

In [ ]:
try:
  a[s2]  # PyTorch currently does not support negative steps
except ValueError as e:
  print(e)

With multidimensional tensors we can perform **multidimensional slicing**:

In [ ]:
a = torch.arange(10).reshape(2, 5)
a

In [ ]:
# Take the second column
a[:, 1]

In [ ]:
# Take the last column
a[:, -1]

In [ ]:
# Take a slice from the last row
a[-1, -3:]

You can **assign** to sliced tensors, modifying the original tensor.

Actually, indexing and slicing operations do their best to return tensors that **share the underlying data** with the original tensor.

In [ ]:
a = torch.arange(10).reshape(2, 5)
a

In [ ]:
b = a[0:2, 1:3]
b

In [ ]:
b[-1, :] = -999
b

In [ ]:
# The original tensor has been modified
a

In [ ]:
a[-1, -1] = -1
a

> **NOTE**
>
> Indexing with **integers yields lower rank tensors**

In [ ]:
a = torch.arange(12).reshape(3, 4)
print_arr(a)

In [ ]:
# Rank 1 view of the second row of a
row_r1 = a[1, :]
print_arr(row_r1)

In [ ]:
# Rank 2 view of the second row of a
row_r2 = a[1:2, :]
print_arr(row_r2)

In [ ]:
# Rank 2 view of the second row of a
row_r3 = a[[1], :]
print_arr(row_r3)

In [ ]:
# Same with the columns
print_arr(a[:, 1])
print_arr(a[:, [1]])

## **Integer array indexing**

It is a generalization of the slice: when you slice, the resulting tensor view will always be a subarray of the original tensor.

Integer array indexing allows you to construct arbitrary tensors, using the data from another tensor

In [ ]:
a = torch.arange(1, 7).reshape(3, 2)
print_arr(a)

In [ ]:
# Example of integer array indexing
# The returned array will have shape (3,)
b = a[[0, 1, 2], [0, 1, 0]]
print_arr(b)

In [ ]:
# Equivalent to
v1, v2, v3 = a[0, 0], a[1, 1], a[2, 0]
b = torch.tensor([v1, v2, v3])
print_arr(b)

In [ ]:
# You can re-use the same element of the source tensor multiple times!
print_arr(a[[0, 0], [1, 1]])
print_arr(torch.tensor([a[0, 1], a[0, 1]]))

In [ ]:
# You can use another tensor to perform the indexing,
# as long as they have dtype=torch.int64 type
i = torch.ones(3, dtype=torch.int64)
i

In [ ]:
j = torch.tensor([0, 1, 0])
j

In [ ]:
out = a[i, j]

print_arr(a, out)

> **EXERCISE**
>
> Change one element in each row of a tensor $X \in R^{4 \times 3}$ to following values:
>
> `X[0,2] = -1`
>
> `X[1,1] = 0`
>
> `X[2,0] = 1`
>
> `X[3,1] = 2`



In [ ]:
# TODO

> **NOTE**
>
> **Slice indexing vs Array indexing**


In [ ]:
a = torch.arange(16).reshape(4, 4)
a

In [ ]:
a[0:3, 0:3]

In [ ]:
a[[0, 1, 2], [0, 1, 2]]

In [ ]:
a[0:5:2, 0:5:2]

## **Boolean array indexing**

This type of indexing is used to select the elements of a tensor that satisfy some condition (similar to MATLAB's logical indexing):

In [ ]:
a = torch.arange(6).reshape(3, 2)
a

In [ ]:
bool_idx = (a > 2)
bool_idx

In [ ]:
a[bool_idx]

If you want to know more about indexing in PyTorch and Numpy read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

> **EXERCISE**
>
> Build a function, which creates a 3D tensor in $X \in R^{k \times k \times k}$ that has ones along the 3D-diagonal and zeros elsewhere, i.e. a 3D identity.

In [ ]:
def create_3d_identity(k):
    # Create a k x k x k tensor
    tensor_3d = []

    return tensor_3d

# TODO

k = 4  # Example size
X = create_3d_identity(k)
print(X)

> **EXERCISE**
>
> Build a 3D tensor $X \in R^{w \times h \times 3}$ representing an image $w \times h$ plus the `(r, g, b)` color channel. Assume the color channel is the last dimension in the tensor and each color $c \in [0, 1]$.
>
> Color the image $X$ completely by red, i.e. `(1, 0, 0)` in the `(r, g, b)` format.

In [ ]:
# TODO

> **EXERCISE**
>
> Given the GitHub logo $X \in R^{560 \times 560}$, change the black-ish color into light gray: $0.8$.  Assume the logo is in grey scale, with the color $c \in [0, 1]$ (remember 0 $\to$ black).
>
> Then draw a diagonal and anti-diagonal black line (i.e. an X) on the new image, to mark that the new logo is wrong.

In [ ]:
from skimage import io
import matplotlib.pyplot as plt

image = io.imread('https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png', as_gray=True)
_ = plt.imshow(image, cmap='gray', vmin=0, vmax=1)

In [ ]:
# Change the black into light-gray
X = torch.from_numpy(image.copy())  # PyTorch CPU and Numpy share the memory!
# TODO

_ = plt.imshow(X, cmap='gray', vmin=0, vmax=1)

In [ ]:
# Mark the new image as wrong with a big black X
# TODO

_ = plt.imshow(X, cmap='gray', vmin=0, vmax=1)

## **GPU Support**

One of the key features of PyTorch tensors is their ability to be moved to a GPU for faster computations. Here's how to check for GPU support and move tensors to the GPU.


In [ ]:
# Check for GPU support
if torch.cuda.is_available():
    tensor_e = torch.tensor([10, 11, 12])
    # Move tensor to GPU
    tensor_e_gpu = tensor_e.to('cuda')
    print("Tensor on GPU:", tensor_e_gpu)
else:
    print("GPU is not available.")


In [ ]:
# Another way
# If available use the GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

# Move the tensor to the according device
t = torch.rand((3,3))
t = t.to(device)  # Pay attention to re-assign the variable!
t

In [ ]:
# Construct tensors directly on the GPU memory
t = torch.ones((5, 5), device='cuda')
t

In [ ]:
# Other methods to transfer tensors between devices
t = torch.rand((3,3))
t = t.cuda()
t

In [ ]:
t = t.cpu()
t

# References

This notebook is adapted from or uses following sources:
* DLAI-s2-2020-tutorials, Luca Moschella (moschella@di.uniroma1.it), https://github.com/lucmos/DLAI-s2-2020-tutorials.git